sudo: false
language: java
jdk:
  - oraclejdk9
  - oraclejdk8
  - openjdk7
cache:
  directories:
    - "$HOME/.m2/repository"
before_cache:
  - rm -rf $HOME/.m2/repository/org/joda/convert
# install
install:
  - mvn --version
script:
  - mvn install site -e -B
after_success:
  - if [[ $TRAVIS_TAG =~ ^v.*$ ]] && [ "$TRAVIS_PULL_REQUEST" == "false" ] && [ "$TRAVIS_JDK_VERSION" == "oraclejdk9" ]; then travis_wait 40 mvn clean install site-deploy -e -B --settings .github/maven-settings.xml; fi
# secure keys for GITHUB_TOKEN
env:
  global:
  - secure: JhdRBdy10fH80tpLPp2uF4WBlJXUOMoCpPwNfGlBbUY84LcS+LZsUiJEXj3+Wr1NGBMr9w9mNseANzKR5FLmSsOleJbebLLwe06qJCcpuI5v9ypVSl5UbQmhTDKUr55cMUvOh4hZ2z0oFi6Fb8PpjeaBeWUQhzOcf+ax97uTArE=
