sudo: false
language: java
jdk:
  - openjdk11
  - oraclejdk9
  - oraclejdk8
cache:
  directories:
    - "$HOME/.m2/repository"
before_cache:
  - rm -rf $HOME/.m2/repository/org/joda/convert
# install
install:
  - mvn --version
script:
  - mvn install site -e -B
after_success:
  - if [[ $TRAVIS_TAG =~ ^website.*$ ]] && [ "$TRAVIS_JDK_VERSION" == "openjdk11" ]; then chmod +x ./.github/website.sh; .github/website.sh; fi
  - if [[ $TRAVIS_TAG =~ ^v.*$ ]] && [ "$TRAVIS_PULL_REQUEST" == "false" ] && [ "$TRAVIS_JDK_VERSION" == "openjdk11" ]; then chmod +x ./.github/website.sh; .github/website.sh; fi
# secure keys for GITHUB_TOKEN
env:
  global:
  - secure: JhdRBdy10fH80tpLPp2uF4WBlJXUOMoCpPwNfGlBbUY84LcS+LZsUiJEXj3+Wr1NGBMr9w9mNseANzKR5FLmSsOleJbebLLwe06qJCcpuI5v9ypVSl5UbQmhTDKUr55cMUvOh4hZ2z0oFi6Fb8PpjeaBeWUQhzOcf+ax97uTArE=
