# This file enables the Travis continuous integration system, which
# automatically builds and tests joda-convert for each GitHub commit or 
# pull request on three separate JDKs.
#
# For more information, see https://travis-ci.org

sudo: false

language: java

jdk: 
  - oraclejdk8
  - oraclejdk7
  - openjdk6
